config/routes.rb
VDlib::Application.routes.draw do

  root :to => "video/topic#index"
  match "query/search" => "query#search"

  namespace :video do
    match "region/:id" => "query#region", :as => :region
    match "provider/:id" => "query#provider", :as => :provider
    match "tag/:id" => "query#tag", :as => :tag
    get "topic/:id" => "topic#show", :as => :topic
    get "topic/:id/detail" => "topic#detail", :as => :topic_detail
    get "media/:id" => "media#show", :as => :media
  end
end

app/controllers/video/media_controller.rb
# encoding: utf-8
class Video::MediaController < ApplicationController
  layout "basic"

  # Get one video detail information, which used in the play view page.
  def show
    begin
      @video_item=VMetadata.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render(:file => "#{Rails.root}/public/404.html",
             :status => "404 Not Found")
    end
  end
end

app/controllers/video/topic_controller.rb
class Video::TopicController < ApplicationController
  layout "basic"

  @@per_page=28

  # Get all of the main categories
  def index
    @topics=GTopic.all
  end

  # Display the summary information about the topic and list several videos
  def show
    begin
      @topic_item=GTopic.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render(:file => "#{Rails.root}/public/404.html",
             :status => "404 Not Found")
    end
  end

  # Display one topic and list all the videos page by page
  def detail
    begin
      @gsubtopic=GSubtopic.find(params[:id])
      @videos=@gsubtopic.v_metadatas.paginate(:page => params[:page], :per_page => @@per_page)
    rescue ActiveRecord::RecordNotFound
      render(:file => "#{Rails.root}/public/404.html",
             :status => "404 Not Found")
    end
  end
end

app/helpers/video/media_helper.rb
module Video::MediaHelper
end

app/helpers/video/topic_helper.rb
module Video::TopicHelper
end

app/views/video/media/show.html.erb
<%= javascript_include_tag "video/flowplayer.min.js" %>
<div class="vd-cnt">
  <div class="breadcrumb">
    <ul>
      <li><%= link_to "首页", root_path %> ></li>
      <li><%= link_to @video_item.g_subtopics.first.g_topic.topic_chs, video_topic_path(@video_item.g_subtopics.first.g_topic.id) %>
        >
      </li>
      <li><%= link_to @video_item.g_subtopics.first.topic_chs, video_topic_detail_path(@video_item.g_subtopics.first.id) %>
        >
      </li>
      <li><%= @video_item.gsv_number %> </li>
    </ul>
  </div>
  <div class="media">
    <div class="m-t">
      <h3><%= @video_item.title_chs %> </h3>
      <h4><%= @video_item.title_eng %></h4>
    </div>
    <div id="m_player" class="m-p"></div>
    <script language="JavaScript">
        flowplayer("m_player", "/flowplayer.swf", {
            plugins: {
                controls: {
                    url: '/flowplayer.controls.swf'
                },
                pseudo: {
                    url: "/flowplayer.pseudostreaming.swf"
                }
            },
            clip: {
                // our clip uses pseudostreaming
                provider: 'pseudo',
                url: '<%="/"+@video_item.video_path %>',
                autoPlay: false
            }
        });
    </script>

    <div class="m-mtr">
      <span><%= link_to "视频下载", "/"+@video_item.video_path %></span>
      <% if @video_item.d_metadatas.length!=0 %>
          <span><%= link_to "文档下载", "/"+@video_item.d_metadatas.first.doc_path %></span>
      <% end %>
    </div>
    <div class="m-info">
      <table>
        <tr>
          <td class="ml">
            <span>视频编号：</span>
          </td>
          <td>
            <span><%= @video_item.gsv_number %></span>
          </td>
        </tr>
        <tr>
          <td class="ml">
            <span>视频简介：</span>
          </td>
          <td>
            <span><%= @video_item.description %></span>
          </td>
        </tr>
        <tr>
          <td class="ml">
            <span>拍摄地：</span>
          </td>
          <td>
        <span>
          <% @video_item.g_regions.each_with_index do |r, i| %>
            <%= link_to r.name_chs, video_region_path(r.id) %> <%= '|' if i < (@video_item.g_regions.size-1) %>
          <% end %>
        </span>
          </td>
        </tr>
        <tr>
          <td class="ml">
            <span>影片来源：</span>
          </td>
          <td>
            <span><%= link_to @video_item.v_provider.detail, video_provider_path(@video_item.v_provider.id) %></span>
          </td>
        </tr>
        <tr>
          <td class="ml">
            <span>关键词：</span>
          </td>
          <td>
          <span>
            <% @video_item.g_tags.each_with_index do |t, i| %>
                <%= link_to(t.tag, video_tag_path(t.id)) %> <%= '|' if i < (@video_item.g_tags.size-1) %>
             <% end %>
          </span>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>
<div class="ctg-bar">
  <%= render :partial => "/video/shared/topic_list_html" %>
</div>